### ISSUE TITLE
Register a user

### ISSUE THREAD

**Issue by mislavmatijevic** [foivz/pop-app-backend#6]
# Feature

This feature enables the user to register an account and save their data into the database.

## Description

Consult [FR-1](https://github.com/foivz/pop-app-backend/wiki/SRS#fr-1) and [defined API endpoints](https://github.com/foivz/pop-app-backend/wiki/SRS#212-endpoints).

| Condition | Description |
| ------ | ---------- |
| Given | User has access to the API. |
| When | User sends a POST _request_ to `/api/v2/users` |
| Then | User receives a _response_
| Or | User receives one of the defined errors, ranging 101-106

It was initially planned for password hashing to use MD-5 for salt and SHA-512 for password hash, with salt prefixed to the password. However, that was replaced by a single hash result from BCrypt.

## Request definition

Sample request is made of the following attributes:
| Attribute name | Attribute type | Attribute description |
| --------------- | --------------- | --------------------- |
| first_name | string | At least 1 character long.
| last_name | string | At least 1 character long.
| username | string | Unique, at least 4 characters long.
| email | string | Unique, at least 4 characters long.
| password | string | At least 7 characters long, one number included. |
| role | string | `buyer` or `seller`

JSON of the sample request:
```
{
    "first_name": "Ivan",
    "last_name": "Horvat",
    "username": "ihorvat",
    "email": "ihorvat@foi.hr",
    "password": "test123",
    "role": "buyer"
}
```

## Response definition
Success:
```
{
    "success": true,
    "message": "User \"ihorvat\" registered with ID 57.",
    "data": [
        {
            "id": 57,
            "first_name": "Ivan",
            "last_name": "Horvat",
            "username": "ihorvat",
            "email": "ihorvat@foi.hr",
            "role": "buyer",
            "activated": false
        }
    ]
}
```

Failure:
```
{
    "success": false,
    "message": "Could not register user \"ihorvat\".",
    "error_code": 102,
    "error_message": "ERR_EMAIL_USED: ihorvat@foi.hr"
}
```

**Comment by mislavmatijevic** [comment]
Dear @antoniokunstek,
Would you kindly take a quick look at my changes to the codebase on my branch and see whether that suits you? I tagged you on couple of highlights in the code.
Thanks and hear from you soon!

**Comment by antoniokunstek** [comment]
Dear boss,
I think I answered all your questions. Just message me If I accidentally missed something. I think, I will take a week off this project so I can focus on my master thesis, but If you need me something or if you will have any question, please do not hesitate to ask. I will check daily for messages on this project.

Thanks for understanding!

**Comment by mislavmatijevic** [comment]
Dear boss no.2,

Good luck with your master thesis! I'll implement the standards we've discussed about here and will notify you on any important additions.

Thanks for everything!

**Comment by mislavmatijevic** [comment]
Note that I realized it makes much more sense to make this route "auth/register" (for security purposes). It's edited in the SRS.
