### ISSUE TITLE
Activate or deactivate a user

### ISSUE THREAD

**Issue by mislavmatijevic** [foivz/pop-app-backend#8]
# Feature

This feature enables the Admin user to accept a registration, i.e. to activate an account and enable its log in.
This feature is **admin only**.

## Description

Consult [FR-2](https://github.com/foivz/pop-app-backend/wiki/SRS#fr-2) and [defined API endpoints](https://github.com/foivz/pop-app-backend/wiki/SRS#212-endpoints).

| Condition | Description |
| ------ | ---------- |
| Given | User is an admin and another user has registered. |
| When | Admin sends a PATCH _request_ to `/api/v2/users/{userId}/activated` |
| Then | Admin receives a _response_
| Or | Admin receives one of the defined errors, ranging 201-203

## Request definition

Sample request is made of the following attributes:
| Attribute name | Attribute type | Attribute description |
| --------------- | --------------- | --------------------- |
| activated | bool | `true` means "yes, can log in", while `false` is the opposite

JSON of the sample request:
```
{
    "activated": true
}
```

### Success activating:
```
{
    "success": true,
    "message": "User \"ihorvat\" activated.",
    "data": [
        {
            "id": 57,
            "first_name": "Ivan",
            "last_name": "Horvat",
            "username": "ihorvat",
            "email": "ihorvat@foi.hr",
            "role": "buyer",
            "activated": true
        }
    ]
}
```

### Success deactivating:
```
{
    "success": true,
    "message": "User \"ihorvat\" deactivated.",
    "data": [
        {
            "id": 57,
            "first_name": "Ivan",
            "last_name": "Horvat",
            "username": "ihorvat",
            "email": "ihorvat@foi.hr",
            "role": "buyer",
            "activated": false
        }
    ]
}
```

### Failure example:
```
{
    "success": false,
    "message": "Could not register user \"ihorvat\".",
    "error_code": 202,
    "error_message": "ERR_ALREADY_ACTIVATED: ihorvat"
}
```

**Comment by antoniokunstek** [comment]
Dear Mislav (@mislavmatijevic),

I took on this task and saw a problem during the creation of the controller class. There is a chance that we will be working on the same files. Do you perhaps want me to switch to another issue or will we solve the problem in the future with possible merge conflicts?

I hope the weather is nice on your current location. 😎
Best regards and enjoy!

**Comment by mislavmatijevic** [comment]
Dear Antonio,

Apologies for not responding sooner.

Feel free to work on your task(s) without minding me. I'm slowed down a
bit. 🙂 I'll handle the merge conflicts.

Weather is really nice here on the countryside, thank you!

Kind regards and happy coding!
